# Generated by Django 4.2 on 2023-04-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
