# Generated by Django 4.2 on 2023-05-23 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyment', '0004_alter_billingadress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingadress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
